#!/bin/bash

echo "🌱 Seeding sample data to Google Sheet..."
echo ""
echo "⚠️  Make sure your backend is configured and running"
echo ""
echo "Sample data to add to your Google Sheet:"
echo ""
echo "ROW 2:"
echo "1 | John Doe | john@example.com | active | 1 | $(date -u +"%Y-%m-%dT%H:%M:%S.000Z") | sheet"
echo ""
echo "ROW 3:"
echo "2 | Jane Smith | jane@example.com | pending | 1 | $(date -u +"%Y-%m-%dT%H:%M:%S.000Z") | sheet"
echo ""
echo "ROW 4:"
echo "3 | Bob Wilson | bob@example.com | active | 1 | $(date -u +"%Y-%m-%dT%H:%M:%S.000Z") | sheet"
echo ""
echo "Add these rows to your sheet and watch them sync to MySQL!"
echo ""
echo "To test DB → Sheet sync, run:"
echo "docker exec -it synclayer-mysql mysql -uroot -ppassword synclayer -e \\"
echo "\"INSERT INTO sync_data VALUES ('4', 'Alice Brown', 'alice@example.com', 'active', 1, NOW(3), 'db');\""
